blank_issues_enabled: false
contact_links:
  - name: a8e Discussion
    url: https://github.com/a8e-ai/a8e/discussions
    about: Please ask and answer questions here.
  - name: Report a security vulnerability
    url: https://github.com/a8e-ai/a8e/security/policy
    about: Please report security vulnerabilities here.
